[2025-05-25T05:23:08.988+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:23:09.425+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-10T00:00:00+00:00 [queued]>
[2025-05-25T05:23:10.021+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-10T00:00:00+00:00 [queued]>
[2025-05-25T05:23:10.024+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:23:13.528+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): move_data_file> on 2025-01-10 00:00:00+00:00
[2025-05-25T05:23:13.601+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'move_data_file', 'scheduled__2025-01-10T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpwkfpydjw']
[2025-05-25T05:23:13.621+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask move_data_file
[2025-05-25T05:23:13.605+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=568) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:23:13.632+0000] {standard_task_runner.py:72} INFO - Started process 597 to run task
[2025-05-25T05:23:14.731+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-10T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:23:17.044+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='move_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-10T00:00:00+00:00'
[2025-05-25T05:23:17.050+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:23:16.390+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-25T05:23:16.411+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /tmp/processed_data/ && mv /tmp/data.csv /tmp/processed_data/']
[2025-05-25T05:23:17.847+0000] {subprocess.py:99} INFO - Output:
[2025-05-25T05:23:18.101+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-25T05:23:18.824+0000] {job.py:229} INFO - Heartbeat recovered after 10.82 seconds
[2025-05-25T05:23:19.768+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:23:19.772+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=move_data_file, run_id=scheduled__2025-01-10T00:00:00+00:00, execution_date=20250110T000000, start_date=20250525T052309, end_date=20250525T052319
[2025-05-25T05:23:20.338+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:23:23.264+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-05-25T05:23:23.772+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:23:23.819+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
