[2025-05-25T05:31:41.806+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:31:46.061+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-05-25T05:31:46.513+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-05-25T05:31:46.532+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:31:47.078+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_file> on 2025-03-07 00:00:00+00:00
[2025-05-25T05:31:47.352+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:31:47.394+0000] {standard_task_runner.py:72} INFO - Started process 1292 to run task
[2025-05-25T05:31:47.395+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'generate_file', 'scheduled__2025-03-07T00:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmp_30yf_ct']
[2025-05-25T05:31:47.544+0000] {standard_task_runner.py:105} INFO - Job 185: Subtask generate_file
[2025-05-25T05:31:48.049+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.generate_file scheduled__2025-03-07T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:31:49.328+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='generate_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-07T00:00:00+00:00'
[2025-05-25T05:31:49.332+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:31:48.956+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-25T05:31:49.092+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:31:49.111+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=generate_file, run_id=scheduled__2025-03-07T00:00:00+00:00, execution_date=20250307T000000, start_date=20250525T053146, end_date=20250525T053149
[2025-05-25T05:31:49.519+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:31:50.478+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:31:50.512+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-25T05:31:50.959+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
