[2025-05-25T05:24:23.959+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:24:24.626+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-05-25T05:24:25.141+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-05-25T05:24:25.162+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:24:26.329+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): move_data_file> on 2025-01-13 00:00:00+00:00
[2025-05-25T05:24:26.440+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=633) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:24:26.474+0000] {standard_task_runner.py:72} INFO - Started process 677 to run task
[2025-05-25T05:24:26.647+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'move_data_file', 'scheduled__2025-01-13T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmp7bckj1pq']
[2025-05-25T05:24:26.907+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask move_data_file
[2025-05-25T05:24:40.592+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-13T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:24:42.520+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='move_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T00:00:00+00:00'
[2025-05-25T05:24:42.525+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:24:43.317+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-25T05:24:43.364+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /tmp/processed_data/ && mv /tmp/data.csv /tmp/processed_data/']
[2025-05-25T05:24:43.792+0000] {subprocess.py:99} INFO - Output:
[2025-05-25T05:24:44.130+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-25T05:24:44.431+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:24:44.438+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=move_data_file, run_id=scheduled__2025-01-13T00:00:00+00:00, execution_date=20250113T000000, start_date=20250525T052424, end_date=20250525T052444
[2025-05-25T05:24:44.769+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:24:52.037+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-05-25T05:24:52.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
