[2025-05-25T07:02:49.812+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T07:02:51.128+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-05-25T07:02:51.572+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-05-25T07:02:51.635+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T07:03:00.661+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): move_data_file> on 2025-03-07 00:00:00+00:00
[2025-05-25T07:03:02.000+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1302) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T07:03:02.391+0000] {standard_task_runner.py:72} INFO - Started process 1356 to run task
[2025-05-25T07:03:02.888+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'move_data_file', 'scheduled__2025-03-07T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpa7gz50ec']
[2025-05-25T07:03:02.972+0000] {standard_task_runner.py:105} INFO - Job 194: Subtask move_data_file
[2025-05-25T07:03:07.103+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.move_data_file scheduled__2025-03-07T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T07:03:08.336+0000] {job.py:229} INFO - Heartbeat recovered after 22.59 seconds
[2025-05-25T07:03:11.802+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='move_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-07T00:00:00+00:00'
[2025-05-25T07:03:11.819+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T07:03:10.905+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-25T07:03:10.944+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /tmp/processed_data/ && mv /tmp/data.csv /tmp/processed_data/']
[2025-05-25T07:03:12.287+0000] {subprocess.py:99} INFO - Output:
[2025-05-25T07:03:12.616+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-25T07:03:13.867+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T07:03:13.910+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=move_data_file, run_id=scheduled__2025-03-07T00:00:00+00:00, execution_date=20250307T000000, start_date=20250525T070251, end_date=20250525T070313
[2025-05-25T07:03:14.521+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T07:03:15.437+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-05-25T07:03:16.050+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T07:03:16.115+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
