[2025-05-25T05:14:01.228+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:14:02.113+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file manual__2025-05-25T05:12:06.102429+00:00 [queued]>
[2025-05-25T05:14:02.815+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file manual__2025-05-25T05:12:06.102429+00:00 [queued]>
[2025-05-25T05:14:02.830+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:14:04.195+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_file> on 2025-05-25 05:12:06.102429+00:00
[2025-05-25T05:14:04.460+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=173) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:14:04.556+0000] {standard_task_runner.py:72} INFO - Started process 219 to run task
[2025-05-25T05:14:04.622+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'generate_file', 'manual__2025-05-25T05:12:06.102429+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpc7ovc29p']
[2025-05-25T05:14:04.662+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask generate_file
[2025-05-25T05:14:26.004+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.generate_file manual__2025-05-25T05:12:06.102429+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:14:34.384+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='generate_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T05:12:06.102429+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T05:12:06.102429+00:00'
[2025-05-25T05:14:34.401+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:14:37.452+0000] {job.py:229} INFO - Heartbeat recovered after 40.29 seconds
[2025-05-25T05:14:37.459+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-25T05:14:38.452+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:14:38.465+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=generate_file, run_id=manual__2025-05-25T05:12:06.102429+00:00, execution_date=20250525T051206, start_date=20250525T051402, end_date=20250525T051438
[2025-05-25T05:14:40.788+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:14:42.456+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-05-25T05:14:43.607+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:14:43.636+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
